#!/bin/sh

. aiu_settings

re_safe_video_prefix="$(echo "$aiu_video_prefix" | sed -e 's/[]\/$*.^|[]/\\&/g')"
re_safe_comic_prefix="$(echo "$aiu_comic_prefix" | sed -e 's/[]\/$*.^|[]/\\&/g')"

helpmsg="Usage: aiu <command>
Commands:
    list - lists unwatched episodes
    open - lets you pick an episode using dmenu
    add <filename> - adds a file to the backlog
    add dir - adds all the files in the current directory to the backlog
    configure - opens the settings file using $EDITOR
    conf - shorthand for configure
    help - displays this message"

function aiu_init() {
    if [ ! -d "$aiu_home" ];then
        mkdir "$aiu_home"
    fi
    if [ ! -f "$aiu_home/$aiu_backlog" ];then
        touch "$aiu_home/$aiu_backlog"
    fi
}

function aiu_add() {
    if [ -n "$1" ];then
        name=$(basename "$1")
        re_safe_name="$(echo "$name" | sed -e 's/[]\/$*.^|[]/\\&/g')"
        target="$(find "$aiu_video_library" "$aiu_comic_library" -type f -name "*$re_safe_name*")"
        type=$(file --brief --mime-type "$target")
        case "$type" in
            application/zip|application/rar)
                name=$(echo "$name" | grep -Eo '.*[0-9]+(\.[0-9]+)?')
                display_name=$(echo '${aiu_comic_prefix}'"$name")
                ;;
            *)
                name=$(echo "$name"| grep -Eo '.*-.[0-9]+')
                display_name=$(echo '${aiu_video_prefix}'"$name")
                ;;
        esac
        if [ $(grep -Fcx "$display_name" "$aiu_home/$aiu_backlog") -eq 0 ];then
            echo "$display_name" >> "$aiu_home/$aiu_backlog"
            echo "$name added"
        else
            echo "File already in backlog"
        fi
    else
        echo "Please specify a file to add"
    fi
}

function aiu_add_dir() {
    for i in *; do
        aiu_add "$i"
    done
}

function aiu_open() {
    name="$(aiu_select)"
    if [ $? -eq 0 ]; then
        name="$(echo "$name" | sed -e 's/^\${aiu_video_prefix}//' -e 's/^\${aiu_comic_prefix}//' -e 's/[]\/$*.^|[]/\\&/g')"
        target="$(find "$aiu_video_library" "$aiu_comic_library" -type f -name "*$name*")"
        type=$(file --brief --mime-type "$target")
        case "$type" in
            video/*)
                $aiu_player "$target"
                ;;
            application/zip)
                $aiu_reader "$target"
                ;;
        esac
        sed -i "/$name/d" "$aiu_home/$aiu_backlog"
    fi
}

function aiu_select() {
    if [ -s "$aiu_home/$aiu_backlog" ];then
        series=$(eval "sort << EOF
$(< $aiu_home/$aiu_backlog )
EOF" | sed 's/\(.*\)[#-].*/\1/' | uniq | $aiu_dmenu)
        if [ $? -eq 0 ]; then
            series="$(echo "$series" | sed -r -e "s/^$re_safe_video_prefix/\${aiu_video_prefix}/" -e "s/^$re_safe_comic_prefix/\${aiu_comic_prefix}/")"
            episodes=$(sort "$aiu_home/$aiu_backlog" | grep -F "$series")
            if [ "$aiu_autoplay" == "true" ];then
                echo "$episodes" | sort -g | head -n 1
            else
                echo "$episodes"| $aiu_dmenu
            fi
        else
            exit 1
        fi
    else
        echo -e "The backlog is empty\nTry adding something with 'aiu add'" | $aiu_dmenu && exit 1
    fi
}

case "$1" in
    list)
        sort "$aiu_home/$aiu_backlog" | sed -e 's/^\${aiu_video_prefix}//' -e 's/^\${aiu_comic_prefix}//'
        ;;
    open)
        aiu_open
        ;;
    add)
        aiu_init
        if [ "$2" == "dir" ];then
            aiu_add_dir
        else
            aiu_add "$2"
        fi
        ;;
    configure|conf)
        $EDITOR "$(dirname $(which aiu))/aiu_settings"
        ;;
    help|*)
        echo "$helpmsg"
    ;;
esac
