#!/bin/sh

helpmsg="Usage: aiu <command>
Commands:
    list - lists unwatched episodes
    open - lets you pick an episode using dmenu
    add <filename> - adds a file to the backlog
    add dir - adds all the files in the current directory to the backlog
    configure|conf - opens the settings file using $EDITOR
    clean - removes all entries for which files can't be found from the backlog
    help - displays this message"

aiu_default_settings=$(cat << "_EOF_"
# directory containg your files
aiu_video_library="$HOME/Videos"
aiu_comic_library="$HOME/Comics"

# player used to open files
aiu_player="mpv"

# reader used to open files
aiu_reader="zathura"

# dmenu command to use
aiu_dmenu="dmenu"

# automatically play oldest episode in series
aiu_autoplay="true"

aiu_video_prefix="[V] "

aiu_comic_prefix="[C] "
_EOF_
)

aiu_init() {
    if [ -z "$XDG_CONFIG_HOME" ]; then
      aiu_home="$HOME/.config/aiu"
    else
      aiu_home="$XDG_CONFIG_HOME/aiu"
    fi

    if [ ! -d "$aiu_home" ];then
        mkdir -p "$aiu_home"
    fi

    if [ ! -f "$aiu_home/backlog" ];then
        touch "$aiu_home/backlog"
    fi

    if [ ! -f "$aiu_home/settings" ];then
      echo "$aiu_default_settings" > "$aiu_home/settings"
    fi
}

aiu_add() {
    if [ -n "$1" ];then
        name=$(basename "$1")
        re_safe_name="$(echo "$name" | sed -e 's/[]\/$*.^|[]/\\&/g')"
        target="$(find "$aiu_video_library" "$aiu_comic_library" -type f -name "*$re_safe_name*")"
        type=$(file --brief --mime-type "$target")
        case "$type" in
            application/zip|application/rar)
                name=$(echo "$name" | grep -Eo '.*[0-9]+(\.[0-9]+)?')
                display_name='${aiu_comic_prefix}'"$name"
                ;;
            *)
                name=$(echo "$name" | grep -Eo '.*-.[0-9]+')
                display_name='${aiu_video_prefix}'"$name"
                ;;
        esac
        if ! grep -Fx "$display_name" "$aiu_home/backlog"; then
            echo "$display_name" >> "$aiu_home/backlog"
            echo "$name added"
        else
            echo "File already in backlog"
        fi
    else
        echo "Please specify a file to add"
    fi
}

aiu_add_dir() {
    for i in *; do
        aiu_add "$i"
    done
}

aiu_open() {
    if name="$(aiu_select)"; then
        name="$(echo "$name" | sed -e "s/^${re_safe_video_prefix}//" -e "s/^${re_safe_comic_prefix}//" -e 's/[]\/$*.^|[]/\\&/g')"
        echo $name
        target="$(find "$aiu_video_library" "$aiu_comic_library" -type f -name "*$name*")"
        type=$(file --brief --mime-type "$target")
        case "$type" in
            video/*)
                $aiu_player "$target"
                ;;
            application/zip)
                $aiu_reader "$target"
                ;;
        esac
        sed -i "/$name/d" "$aiu_home/backlog"
    fi
}

aiu_select() {
    if [ -s "$aiu_home/backlog" ];then
      if series=$(sort "$aiu_home"/backlog | sed -e 's/${aiu_video_prefix}/'"$aiu_video_prefix/" -e 's/${aiu_comic_prefix}/'"$aiu_comic_prefix/" -e 's/\(.*\)[#-].*/\1/' | uniq | $aiu_dmenu); then
            series="$(echo "$series" | sed -r -e "s/^$re_safe_video_prefix/\${aiu_video_prefix}/" -e "s/^$re_safe_comic_prefix/\${aiu_comic_prefix}/")"
            episodes=$(sort "$aiu_home/backlog" | grep -F "$series")
            if [ "$aiu_autoplay" = "true" ];then
                echo "$episodes" | sed -e 's/${aiu_video_prefix}/'"$aiu_video_prefix/" -e 's/${aiu_comic_prefix}/'"$aiu_comic_prefix/" | sort -g | head -n 1
            else
                echo "$episodes" | sed -e 's/${aiu_video_prefix}/'"$aiu_video_prefix/" -e 's/${aiu_comic_prefix}/'"$aiu_comic_prefix/" | $aiu_dmenu
            fi
        else
            exit 1
        fi
    else
        printf "%s\n%s" "The backlog is empty" "Try adding something with 'aiu add'" | $aiu_dmenu && exit 1
    fi
}

aiu_clean() {
    sort "$aiu_home/backlog" | sed -e 's/^${aiu_video_prefix}//' -e 's/^${aiu_comic_prefix}//' -e 's/[]\/$*.^|[]/\\&/g' | while read -r name; do
        target="$(find "$aiu_video_library" "$aiu_comic_library" -type f -name "*$name*")"
        if [ -z "$target" ]; then
            sed -i "/$name/d" "$aiu_home/backlog"
        fi
    done
}

aiu_init
. "$aiu_home/settings"
re_safe_video_prefix="$(echo "$aiu_video_prefix" | sed -e 's/[]\/$*.^|[]/\\&/g')"
re_safe_comic_prefix="$(echo "$aiu_comic_prefix" | sed -e 's/[]\/$*.^|[]/\\&/g')"

case "$1" in
    list)
        sort "$aiu_home/backlog" | sed -e 's/^\${aiu_video_prefix}//' -e 's/^\${aiu_comic_prefix}//'
        ;;
    open)
        aiu_open
        ;;
    add)
        if [ "$2" = "dir" ];then
            aiu_add_dir
        else
            aiu_add "$2"
        fi
        ;;
    configure|conf)
        $EDITOR "$aiu_home/settings"
        ;;
    clean)
        aiu_clean
        ;;
    help|*)
        echo "$helpmsg"
        ;;
esac

if [ -n "$(find "$aiu_home" -maxdepth 1 -name 'sed*' -print -quit)" ];then
    rm -f "$aiu_home"/sed*
fi
