#!/bin/sh

. aiu_settings

name="$(aiu_select)"
if [ $? -eq 0 ]; then
    name="$(echo "$name" | sed -r 's/(\[|\])/\\\1/g')"
    target="$(find "$aiu_library" -type f -name "*$name*")"
    $aiu_player "$target"
    sed -i "/$name/d" "$aiu_home/$aiu_backlog"
fi
