#!/bin/sh

. aiu_settings

aiu_init

if [ -n "$1" ];then
    name=$(basename "$1")
    re_safe_name="$(echo "$name" | sed -e 's/[]\/$*.^|[]/\\&/g')"
    target="$(find "$aiu_video_library" "$aiu_comic_library" -type f -name "*$re_safe_name*")"
    type=$(file --brief --mime-type "$target")
    case "$type" in
        application/zip|application/rar)
            name=$(echo '${aiu_comic_prefix}'"$name" | grep -Eo '.*[0-9]+(\.[0-9]+)?')
            ;;
        *)
            name=$(echo '${aiu_video_prefix}'"$name"| grep -Eo '\[.*\].*-.[0-9]+')
            ;;
    esac
    if [ $(grep -Fcx "$name" "$aiu_home/$aiu_backlog") -eq 0 ];then
        echo "$name" >> "$aiu_home/$aiu_backlog"
        echo "$name added"
    else
        echo "File already in backlog"
    fi
else
    echo "Please specify a file to add"
fi
